### ISSUE TITLE
i don't know how to pull request

### ISSUE THREAD

**Issue by 83900** [PeizheZhao/Note-Git#2]
我不知道如何pr

**Comment by PeizheZhao** [comment]
参考这个
[git、github 保姆级教程入门，工作和协作必备技术，github提交pr - pull request](https://www.bilibili.com/video/BV1s3411g7PS/?spm_id_from=333.788.top_right_bar_window_default_collection.content.click&vd_source=9569401fceb5dd222cf4b52f39408100)
